# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KevCaz's home page
email: kevin.cazelles@um2.fr
phone: "+1 418 723-1986 (1569)"
description: > # this means to ignore newlines until "baseurl:"
  Kevin Cazelles home page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kevincazelles.fr" # the base hostname & protocol for your site
# twitter_username: jekyllrb
orcid: 0000-0001-6619-9874
github_username: KevCaz
rg_username: Kevin_Cazelles
sass:
   sass_dir: _sass
   style: compressed

# Build settings
markdown: kramdown

# Site settings
update: 21 jan 2017

# github_username: KevCaz
